trigger:
  tags:
    include:
      - v*

  paths:
    exclude:
      - README.md

jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Bash@3
        displayName: Installing pip-related packages
        inputs:
          targetType: inline
          script: pip3 install setuptools wheel

      - task: Bash@3
        displayName: Installing required utils
        inputs:
          targetType: inline
          script: pip3 install virtualenv awscli --user

      - task: Bash@3
        displayName: Bundling package for deployment
        inputs:
          targetType: filePath
          filePath: ./ci/build.sh

      - task: Bash@3
        displayName: Deploying
        inputs:
          targetType: inline
          script: 'PATH=$PATH:$HOME/.local/bin make deploy'
        env:
          AWS_DEFAULT_REGION: $(aws.region)
          AWS_ACCESS_KEY_ID: $(aws.access_key)
          AWS_SECRET_ACCESS_KEY: $(aws.secret_key)
          AWS_LAMBDA_NAME: $(aws.lambda_name)
          AWS_S3_BUCKET: $(aws.s3_bucket)
